const ActionType = {
  GET_DATA: "GET_DATA",
  // ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  // REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  GET_NUMBER_CART: "GET_NUMBER_CART",
  ADD_CART: "ADD_CART",
  UPDATE_CART: "UPDATE_CART",
  DELETE_CART: "DELETE_CART",
  TEMP_ITEM: "TEMP_ITEM",
};

export default ActionType;
